version: '2'
services:
    db:
      image: mysql
      container_name: test-mysql
      ports: 
      - "6603:3306"
      environment: 
        MYSQL_ROOT_PASSWORD: 1234
      volumes: 
        - /storage/docker/mysql-datadir:/var/lib/mysql
